name: a_movie_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.6
  eva_icons_flutter: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^3.0.1+1
  font_awesome_flutter: ^8.8.1
  intl: ^0.17.0
  page_indicator: ^0.3.0
  rxdart: ^0.27.5

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
